services:
  city2tabula:
    container_name: city2tabula-environment
    build:
      context: ./..
      dockerfile: environment/Dockerfile
    env_file: docker.env        # load environment variables into container
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./../data:/app/data        # mount full project for development
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility
    ports:
      - "${HOST_PORT}:5000"        # map host port (configurable) to container port 8080
    command: bash         # start an interactive shell for development
